### ISSUE TITLE
A bit improvements

### ISSUE THREAD

**Issue by s0i37** [sharkdp/binocle#31]
Hello.
Very good.
But probably need:
 - scale bar (in pixels window)
 - hex address (in hex window)
 - zoom out for large files, like a memory dumps

**Comment by sharkdp** [comment]
thank you for your feedback!

> hex address (in hex window)

sounds good

> zoom out for large files, like a memory dumps

yes, that would be nice

> scale bar (in pixels window)

could you elaborate?

**Comment by s0i37** [comment]
scale bar (in pixels window)
It like this
![1](https://user-images.githubusercontent.com/22872513/140045299-d00d279c-415e-455f-8a5f-f8927fd134c0.png)
:

**Comment by sharkdp** [comment]
Alright, thank you! It would be great if you could open individual requests for each of these issues - and close this afterwards.

**Comment by s0i37** [comment]
https://github.com/sharkdp/binocle/issues/36
https://github.com/sharkdp/binocle/issues/37
https://github.com/sharkdp/binocle/issues/38
