### ISSUE TITLE
[request] Finer value adjustments 

### ISSUE THREAD

**Issue by derVedro** [sharkdp/binocle#42]
I would like a finer way of setting some values like width, I'm thinking of steps of one, maybe with the mouse wheel or a keyboard shortcut.

**Comment by sharkdp** [comment]
You can press "Shift" for finer control

**Comment by derVedro** [comment]
It looks like shift key has no effect in binocle 0.2.0 under ubuntu 20.04.

**Comment by sharkdp** [comment]
you need to click on the number, not the scrollbar:

![image](https://user-images.githubusercontent.com/4209276/149586982-c4157afa-7af1-4e81-a4b7-c31f1c1932d9.png)

**Comment by derVedro** [comment]
yes, okay, I get it. It's just one order of magnitude finer. I simply miss it.
