### ISSUE TITLE
Error: No suitable `wgpu::Adapter` found.

### ISSUE THREAD

**Issue by mb720** [sharkdp/binocle#50]
Hi and thanks a lot for binocle!

I just tried binocle on a Lenovo X220 running Arch Linux:

    $ RUST_LOG=trace binocle /bin/ls
    [2023-05-18T19:16:57Z WARN  wgpu_hal::vulkan::instance] create_instance: VkError(ERROR_INCOMPATIBLE_DRIVER)
    warning: queue 0x563cc86a6340 destroyed while proxies still attached:
      xdg_wm_base@20 still attached
      wl_surface@19 still attached
      wl_output@14 still attached
      wl_output@13 still attached
      wl_seat@12 still attached
      xdg_activation_v1@11 still attached
      zwp_text_input_manager_v3@10 still attached
      zwp_pointer_constraints_v1@9 still attached
      zwp_relative_pointer_manager_v1@8 still attached
      zxdg_decoration_manager_v1@7 still attached
      wl_subcompositor@6 still attached
      wl_compositor@5 still attached
      wl_shm@4 still attached
      wl_registry@2 still attached
    Error: No suitable `wgpu::Adapter` found.

Is there anything I can do to debug this?

Thanks!

**Comment by sharkdp** [comment]
Looks like maybe you are missing some vulkan drivers? See https://wiki.archlinux.org/title/Vulkan

I'm on Arch as well and it works fine for me.

**Comment by mb720** [comment]
@sharkdp: Thanks, that was it.

Since I'm on Sandy Bridge and my "graphics card" acccording `lspci | grep VGA` is

>00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)

I couldn't just install [`vulkan-intel`](https://archlinux.org/packages/extra/x86_64/vulkan-intel/) since Vulkan [is only supported since Ivy Bridge](https://wiki.archlinux.org/title/Intel_graphics#Installation).

Instead of using `vulkan-intel`, I followed [this advice](https://bbs.archlinux.org/viewtopic.php?id=285395) and installed [`vulkan-swrast`](https://archlinux.org/packages/extra/x86_64/vulkan-swrast/) which made binocle run.

Unfortunately, binocle uses two cores all the time, without me interacting with the GUI.

But thanks again for helping out. 👍

**Comment by sharkdp** [comment]
> Unfortunately, binocle uses two cores all the time, without me interacting with the GUI.

Yeah, binocle is quite heavy on CPU usage. It's currently rendering the UI and the visualization in every frame.

But two cores full time?! For me it's one CPU at ~70%.

**Comment by sharkdp** [comment]
Ahh... swrast is the software rasterizer. That's probably why. That will make the UI quite laggy, I assume.

**Comment by overtube** [comment]
**`
[2023-11-03T17:09:31Z ERROR wgpu_hal::vulkan::instance] enumerate_adapters: Initialization of a object has failed
Error: No suitable `wgpu::Adapter` found.
`**

**`pacman -Q vulkan-radeon`**
`vulkan-radeon 1:23.2.1-2`

**`pacman -Q lib32-vulkan-radeon`**
`lib32-vulkan-radeon 1:23.2.1-2`

**`pacman -Q mesa`**
`mesa 1:23.2.1-2`

**`pacman -Q lib32-mesa`**
`lib32-mesa 1:23.2.1-2`

**`pacman -Q vulkan-mesa-layers`**
`vulkan-mesa-layers 1:23.2.1-2`

**what wrong?** **why don't work?**

**Comment by overtube** [comment]
pacman -S **`vulkan-swrast`** and all can be work
