### ISSUE TITLE
Package a macOS .app/.dmg

### ISSUE THREAD

**Issue by wilsonlmh** [sharkdp/binocle#52]
Hello! Amazing app! This is absolutely gorgeous!
I just wonder if there's any plan to package this into a macOS .app bundle?
I'm not familiar with rust but looks like this can help?
https://github.com/burtonageo/cargo-bundle

Maybe also add some features later sometime, like a menubar to open/close file. I would like to help on this (after I read more about rust, I know zero about it).
Much appreciated!

**Comment by sharkdp** [comment]
Thank you for the feedback.

I am not a macOS user and I definitely won't be working on packaging for macOS, but if someone does, I'm happy to add instructions to the README.
